make http client configurable, closes #30
openzipkin-contrib/brave-ratpack pull request #31
Opened 2019-08-21 21:35 UTC by drmaas

2019-08-22 14:44 UTC, drmaas commented
@llinder wonder if you can take a look

2019-08-24 21:02 UTC, llinder requested changes
Looks good.  Only thing I would like is to avoid the Ratpack version change if possible.

@jeff-blaisdell @Bijnagte might also be interested or have input on the Guice bindings.

2019-08-24 21:02 UTC, llinder commented on pom.xml
> -    <ratpack.version>1.6.0</ratpack.version>
Is there a reason to bump the version?  We still have a number of services that may be using Ratpack 1.6 and accidentally importing a new version may cause problems.

2019-08-29 14:31 UTC, drmaas commented
@llinder reverted to 1.6.0 :)

2019-09-03 17:03 UTC, merged